FROM python:3.7-slim

MAINTAINER Alice ROGIER <alice.rogier-ext@aphp.fr>

ENV WD /home/quickumls

RUN apt-get update

RUN apt-get install -y python3-dev gcc g++ locales locales-all

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
	locale-gen

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8 

RUN pip install quickumls nltk six


RUN mkdir /home/quickumls

WORKDIR /home/quickumls


RUN mkdir $WD/config
RUN mkdir $WD/umls_data
RUN mkdir $WD/src
RUN mkdir $WD/tmp
WORKDIR $WD/tmp

COPY src/ $WD/src

RUN apt-get install -y curl procps
CMD ["python","/home/quickumls/src/client.py ","--serverName ","$server_name", "--inputFile ","$input"]
